"""initial tables

Revision ID: 97b059705b47
Revises: 66c18b8f918c
Create Date: 2026-04-22 19:00:34.203634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b059705b47'
down_revision: Union[str, Sequence[str], None] = '66c18b8f918c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('sem', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('pass_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'pass_year')
    op.drop_column('profiles', 'sem')
    op.drop_column('profiles', 'branch')
    # ### end Alembic commands ###
